#ifndef LIL_CURRENT_VERSION_INCLUDED
#define LIL_CURRENT_VERSION_INCLUDED

#define LIL_CURRENT_VERSION_VALUE 42
#define LIL_CURRENT_VERSION_MAJOR 1
#define LIL_CURRENT_VERSION_MINOR 7
#define LIL_CURRENT_VERSION_PATCH 2

#endif  // LIL_CURRENT_VERSION_INCLUDED
