#ifndef LIL_CURRENT_VERSION_INCLUDED
#define LIL_CURRENT_VERSION_INCLUDED

#define LIL_CURRENT_VERSION_VALUE 45
#define LIL_CURRENT_VERSION_MAJOR 2
#define LIL_CURRENT_VERSION_MINOR 1
#define LIL_CURRENT_VERSION_PATCH 4

#endif  // LIL_CURRENT_VERSION_INCLUDED
